// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/chat/chat.proto

package chat

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LoginRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_1b2230346337dc13, []int{0}
}
func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (dst *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(dst, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type LoginResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_1b2230346337dc13, []int{1}
}
func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (dst *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(dst, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type LogoutRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutRequest) Reset()         { *m = LogoutRequest{} }
func (m *LogoutRequest) String() string { return proto.CompactTextString(m) }
func (*LogoutRequest) ProtoMessage()    {}
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_1b2230346337dc13, []int{2}
}
func (m *LogoutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutRequest.Unmarshal(m, b)
}
func (m *LogoutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutRequest.Marshal(b, m, deterministic)
}
func (dst *LogoutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutRequest.Merge(dst, src)
}
func (m *LogoutRequest) XXX_Size() int {
	return xxx_messageInfo_LogoutRequest.Size(m)
}
func (m *LogoutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutRequest proto.InternalMessageInfo

func (m *LogoutRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type LogoutResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutResponse) Reset()         { *m = LogoutResponse{} }
func (m *LogoutResponse) String() string { return proto.CompactTextString(m) }
func (*LogoutResponse) ProtoMessage()    {}
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_1b2230346337dc13, []int{3}
}
func (m *LogoutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutResponse.Unmarshal(m, b)
}
func (m *LogoutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutResponse.Marshal(b, m, deterministic)
}
func (dst *LogoutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutResponse.Merge(dst, src)
}
func (m *LogoutResponse) XXX_Size() int {
	return xxx_messageInfo_LogoutResponse.Size(m)
}
func (m *LogoutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutResponse proto.InternalMessageInfo

type RequestStream struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestStream) Reset()         { *m = RequestStream{} }
func (m *RequestStream) String() string { return proto.CompactTextString(m) }
func (*RequestStream) ProtoMessage()    {}
func (*RequestStream) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_1b2230346337dc13, []int{4}
}
func (m *RequestStream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestStream.Unmarshal(m, b)
}
func (m *RequestStream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestStream.Marshal(b, m, deterministic)
}
func (dst *RequestStream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestStream.Merge(dst, src)
}
func (m *RequestStream) XXX_Size() int {
	return xxx_messageInfo_RequestStream.Size(m)
}
func (m *RequestStream) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestStream.DiscardUnknown(m)
}

var xxx_messageInfo_RequestStream proto.InternalMessageInfo

func (m *RequestStream) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ResponseStream struct {
	Timestamp *timestamp.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to Event:
	//	*ResponseStream_ClientLogin
	//	*ResponseStream_ClientLogout
	//	*ResponseStream_ClientMessage
	//	*ResponseStream_ServerShutdown
	Event                isResponseStream_Event `protobuf_oneof:"event"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ResponseStream) Reset()         { *m = ResponseStream{} }
func (m *ResponseStream) String() string { return proto.CompactTextString(m) }
func (*ResponseStream) ProtoMessage()    {}
func (*ResponseStream) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_1b2230346337dc13, []int{5}
}
func (m *ResponseStream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseStream.Unmarshal(m, b)
}
func (m *ResponseStream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseStream.Marshal(b, m, deterministic)
}
func (dst *ResponseStream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseStream.Merge(dst, src)
}
func (m *ResponseStream) XXX_Size() int {
	return xxx_messageInfo_ResponseStream.Size(m)
}
func (m *ResponseStream) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseStream.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseStream proto.InternalMessageInfo

type isResponseStream_Event interface {
	isResponseStream_Event()
}

type ResponseStream_ClientLogin struct {
	ClientLogin *ResponseStream_Login `protobuf:"bytes,2,opt,name=client_login,json=clientLogin,proto3,oneof"`
}
type ResponseStream_ClientLogout struct {
	ClientLogout *ResponseStream_Logout `protobuf:"bytes,3,opt,name=client_logout,json=clientLogout,proto3,oneof"`
}
type ResponseStream_ClientMessage struct {
	ClientMessage *ResponseStream_Message `protobuf:"bytes,4,opt,name=client_message,json=clientMessage,proto3,oneof"`
}
type ResponseStream_ServerShutdown struct {
	ServerShutdown *ResponseStream_Shutdown `protobuf:"bytes,5,opt,name=server_shutdown,json=serverShutdown,proto3,oneof"`
}

func (*ResponseStream_ClientLogin) isResponseStream_Event()    {}
func (*ResponseStream_ClientLogout) isResponseStream_Event()   {}
func (*ResponseStream_ClientMessage) isResponseStream_Event()  {}
func (*ResponseStream_ServerShutdown) isResponseStream_Event() {}

func (m *ResponseStream) GetEvent() isResponseStream_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *ResponseStream) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *ResponseStream) GetClientLogin() *ResponseStream_Login {
	if x, ok := m.GetEvent().(*ResponseStream_ClientLogin); ok {
		return x.ClientLogin
	}
	return nil
}

func (m *ResponseStream) GetClientLogout() *ResponseStream_Logout {
	if x, ok := m.GetEvent().(*ResponseStream_ClientLogout); ok {
		return x.ClientLogout
	}
	return nil
}

func (m *ResponseStream) GetClientMessage() *ResponseStream_Message {
	if x, ok := m.GetEvent().(*ResponseStream_ClientMessage); ok {
		return x.ClientMessage
	}
	return nil
}

func (m *ResponseStream) GetServerShutdown() *ResponseStream_Shutdown {
	if x, ok := m.GetEvent().(*ResponseStream_ServerShutdown); ok {
		return x.ServerShutdown
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ResponseStream) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ResponseStream_OneofMarshaler, _ResponseStream_OneofUnmarshaler, _ResponseStream_OneofSizer, []interface{}{
		(*ResponseStream_ClientLogin)(nil),
		(*ResponseStream_ClientLogout)(nil),
		(*ResponseStream_ClientMessage)(nil),
		(*ResponseStream_ServerShutdown)(nil),
	}
}

func _ResponseStream_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ResponseStream)
	// event
	switch x := m.Event.(type) {
	case *ResponseStream_ClientLogin:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ClientLogin); err != nil {
			return err
		}
	case *ResponseStream_ClientLogout:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ClientLogout); err != nil {
			return err
		}
	case *ResponseStream_ClientMessage:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ClientMessage); err != nil {
			return err
		}
	case *ResponseStream_ServerShutdown:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ServerShutdown); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("ResponseStream.Event has unexpected type %T", x)
	}
	return nil
}

func _ResponseStream_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ResponseStream)
	switch tag {
	case 2: // event.client_login
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ResponseStream_Login)
		err := b.DecodeMessage(msg)
		m.Event = &ResponseStream_ClientLogin{msg}
		return true, err
	case 3: // event.client_logout
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ResponseStream_Logout)
		err := b.DecodeMessage(msg)
		m.Event = &ResponseStream_ClientLogout{msg}
		return true, err
	case 4: // event.client_message
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ResponseStream_Message)
		err := b.DecodeMessage(msg)
		m.Event = &ResponseStream_ClientMessage{msg}
		return true, err
	case 5: // event.server_shutdown
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ResponseStream_Shutdown)
		err := b.DecodeMessage(msg)
		m.Event = &ResponseStream_ServerShutdown{msg}
		return true, err
	default:
		return false, nil
	}
}

func _ResponseStream_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ResponseStream)
	// event
	switch x := m.Event.(type) {
	case *ResponseStream_ClientLogin:
		s := proto.Size(x.ClientLogin)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ResponseStream_ClientLogout:
		s := proto.Size(x.ClientLogout)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ResponseStream_ClientMessage:
		s := proto.Size(x.ClientMessage)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ResponseStream_ServerShutdown:
		s := proto.Size(x.ServerShutdown)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type ResponseStream_Login struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseStream_Login) Reset()         { *m = ResponseStream_Login{} }
func (m *ResponseStream_Login) String() string { return proto.CompactTextString(m) }
func (*ResponseStream_Login) ProtoMessage()    {}
func (*ResponseStream_Login) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_1b2230346337dc13, []int{5, 0}
}
func (m *ResponseStream_Login) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseStream_Login.Unmarshal(m, b)
}
func (m *ResponseStream_Login) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseStream_Login.Marshal(b, m, deterministic)
}
func (dst *ResponseStream_Login) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseStream_Login.Merge(dst, src)
}
func (m *ResponseStream_Login) XXX_Size() int {
	return xxx_messageInfo_ResponseStream_Login.Size(m)
}
func (m *ResponseStream_Login) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseStream_Login.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseStream_Login proto.InternalMessageInfo

func (m *ResponseStream_Login) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ResponseStream_Logout struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseStream_Logout) Reset()         { *m = ResponseStream_Logout{} }
func (m *ResponseStream_Logout) String() string { return proto.CompactTextString(m) }
func (*ResponseStream_Logout) ProtoMessage()    {}
func (*ResponseStream_Logout) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_1b2230346337dc13, []int{5, 1}
}
func (m *ResponseStream_Logout) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseStream_Logout.Unmarshal(m, b)
}
func (m *ResponseStream_Logout) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseStream_Logout.Marshal(b, m, deterministic)
}
func (dst *ResponseStream_Logout) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseStream_Logout.Merge(dst, src)
}
func (m *ResponseStream_Logout) XXX_Size() int {
	return xxx_messageInfo_ResponseStream_Logout.Size(m)
}
func (m *ResponseStream_Logout) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseStream_Logout.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseStream_Logout proto.InternalMessageInfo

func (m *ResponseStream_Logout) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ResponseStream_Message struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseStream_Message) Reset()         { *m = ResponseStream_Message{} }
func (m *ResponseStream_Message) String() string { return proto.CompactTextString(m) }
func (*ResponseStream_Message) ProtoMessage()    {}
func (*ResponseStream_Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_1b2230346337dc13, []int{5, 2}
}
func (m *ResponseStream_Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseStream_Message.Unmarshal(m, b)
}
func (m *ResponseStream_Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseStream_Message.Marshal(b, m, deterministic)
}
func (dst *ResponseStream_Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseStream_Message.Merge(dst, src)
}
func (m *ResponseStream_Message) XXX_Size() int {
	return xxx_messageInfo_ResponseStream_Message.Size(m)
}
func (m *ResponseStream_Message) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseStream_Message.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseStream_Message proto.InternalMessageInfo

func (m *ResponseStream_Message) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ResponseStream_Message) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ResponseStream_Shutdown struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseStream_Shutdown) Reset()         { *m = ResponseStream_Shutdown{} }
func (m *ResponseStream_Shutdown) String() string { return proto.CompactTextString(m) }
func (*ResponseStream_Shutdown) ProtoMessage()    {}
func (*ResponseStream_Shutdown) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_1b2230346337dc13, []int{5, 3}
}
func (m *ResponseStream_Shutdown) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseStream_Shutdown.Unmarshal(m, b)
}
func (m *ResponseStream_Shutdown) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseStream_Shutdown.Marshal(b, m, deterministic)
}
func (dst *ResponseStream_Shutdown) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseStream_Shutdown.Merge(dst, src)
}
func (m *ResponseStream_Shutdown) XXX_Size() int {
	return xxx_messageInfo_ResponseStream_Shutdown.Size(m)
}
func (m *ResponseStream_Shutdown) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseStream_Shutdown.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseStream_Shutdown proto.InternalMessageInfo

func init() {
	proto.RegisterType((*LoginRequest)(nil), "chat.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "chat.LoginResponse")
	proto.RegisterType((*LogoutRequest)(nil), "chat.LogoutRequest")
	proto.RegisterType((*LogoutResponse)(nil), "chat.LogoutResponse")
	proto.RegisterType((*RequestStream)(nil), "chat.RequestStream")
	proto.RegisterType((*ResponseStream)(nil), "chat.ResponseStream")
	proto.RegisterType((*ResponseStream_Login)(nil), "chat.ResponseStream.Login")
	proto.RegisterType((*ResponseStream_Logout)(nil), "chat.ResponseStream.Logout")
	proto.RegisterType((*ResponseStream_Message)(nil), "chat.ResponseStream.Message")
	proto.RegisterType((*ResponseStream_Shutdown)(nil), "chat.ResponseStream.Shutdown")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ChatClient is the client API for Chat service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChatClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error)
	Stream(ctx context.Context, opts ...grpc.CallOption) (Chat_StreamClient, error)
}

type chatClient struct {
	cc *grpc.ClientConn
}

func NewChatClient(cc *grpc.ClientConn) ChatClient {
	return &chatClient{cc}
}

func (c *chatClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/chat.Chat/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error) {
	out := new(LogoutResponse)
	err := c.cc.Invoke(ctx, "/chat.Chat/Logout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) Stream(ctx context.Context, opts ...grpc.CallOption) (Chat_StreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Chat_serviceDesc.Streams[0], "/chat.Chat/Stream", opts...)
	if err != nil {
		return nil, err
	}
	x := &chatStreamClient{stream}
	return x, nil
}

type Chat_StreamClient interface {
	Send(*RequestStream) error
	Recv() (*ResponseStream, error)
	grpc.ClientStream
}

type chatStreamClient struct {
	grpc.ClientStream
}

func (x *chatStreamClient) Send(m *RequestStream) error {
	return x.ClientStream.SendMsg(m)
}

func (x *chatStreamClient) Recv() (*ResponseStream, error) {
	m := new(ResponseStream)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ChatServer is the server API for Chat service.
type ChatServer interface {
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	Logout(context.Context, *LogoutRequest) (*LogoutResponse, error)
	Stream(Chat_StreamServer) error
}

func RegisterChatServer(s *grpc.Server, srv ChatServer) {
	s.RegisterService(&_Chat_serviceDesc, srv)
}

func _Chat_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.Chat/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.Chat/Logout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).Logout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChatServer).Stream(&chatStreamServer{stream})
}

type Chat_StreamServer interface {
	Send(*ResponseStream) error
	Recv() (*RequestStream, error)
	grpc.ServerStream
}

type chatStreamServer struct {
	grpc.ServerStream
}

func (x *chatStreamServer) Send(m *ResponseStream) error {
	return x.ServerStream.SendMsg(m)
}

func (x *chatStreamServer) Recv() (*RequestStream, error) {
	m := new(RequestStream)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Chat_serviceDesc = grpc.ServiceDesc{
	ServiceName: "chat.Chat",
	HandlerType: (*ChatServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _Chat_Login_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _Chat_Logout_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _Chat_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/chat/chat.proto",
}

func init() { proto.RegisterFile("pkg/chat/chat.proto", fileDescriptor_chat_1b2230346337dc13) }

var fileDescriptor_chat_1b2230346337dc13 = []byte{
	// 414 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0x4d, 0x4f, 0xea, 0x40,
	0x14, 0x6d, 0xa1, 0x85, 0xc7, 0x05, 0xfa, 0x5e, 0x06, 0x16, 0x4d, 0xe1, 0x45, 0xd3, 0xc4, 0x04,
	0x37, 0xc5, 0x60, 0x8c, 0xba, 0x32, 0xc1, 0x98, 0x74, 0xa1, 0x9b, 0xe2, 0x9e, 0x14, 0x1c, 0x0b,
	0x81, 0x76, 0x6a, 0x67, 0x8a, 0x7f, 0xca, 0x3f, 0xe6, 0xbf, 0x30, 0xcc, 0x47, 0x4b, 0x93, 0xba,
	0x69, 0x3a, 0x77, 0xce, 0x39, 0xf7, 0x9e, 0x3b, 0x07, 0x06, 0xe9, 0x2e, 0x9a, 0xae, 0x37, 0x21,
	0xe3, 0x1f, 0x2f, 0xcd, 0x08, 0x23, 0xc8, 0x38, 0xfe, 0x3b, 0x67, 0x11, 0x21, 0xd1, 0x1e, 0x4f,
	0x79, 0x6d, 0x95, 0xbf, 0x4f, 0xd9, 0x36, 0xc6, 0x94, 0x85, 0x71, 0x2a, 0x60, 0xae, 0x0b, 0xbd,
	0x67, 0x12, 0x6d, 0x93, 0x00, 0x7f, 0xe4, 0x98, 0x32, 0x84, 0xc0, 0x48, 0xc2, 0x18, 0xdb, 0xfa,
	0xb9, 0x3e, 0xe9, 0x04, 0xfc, 0xdf, 0xbd, 0x80, 0xbe, 0xc4, 0xd0, 0x94, 0x24, 0x14, 0xa3, 0x21,
	0x98, 0x8c, 0xec, 0x70, 0x22, 0x51, 0xe2, 0x20, 0x61, 0x24, 0x67, 0x4a, 0xab, 0x1e, 0xf6, 0x0f,
	0x2c, 0x05, 0x13, 0x72, 0xee, 0x25, 0xf4, 0x25, 0x65, 0xc1, 0x32, 0x1c, 0xc6, 0xc8, 0x86, 0x76,
	0x8c, 0x29, 0x0d, 0x23, 0x35, 0x87, 0x3a, 0xba, 0xdf, 0x4d, 0xb0, 0x14, 0x4f, 0x82, 0xef, 0xa0,
	0x53, 0x98, 0xe2, 0xf0, 0xee, 0xcc, 0xf1, 0x84, 0x6d, 0x4f, 0xd9, 0xf6, 0x5e, 0x15, 0x22, 0x28,
	0xc1, 0xe8, 0x01, 0x7a, 0xeb, 0xfd, 0x16, 0x27, 0x6c, 0xb9, 0x3f, 0xda, 0xb3, 0x1b, 0x92, 0xcc,
	0xb7, 0x58, 0xed, 0xe2, 0xf1, 0x05, 0xf8, 0x5a, 0xd0, 0x15, 0x0c, 0x7e, 0x44, 0x73, 0xe8, 0x97,
	0x02, 0x24, 0x67, 0x76, 0x93, 0x2b, 0x8c, 0x7e, 0x53, 0x20, 0x39, 0xf3, 0xb5, 0xa0, 0x57, 0x48,
	0x90, 0x9c, 0xa1, 0x27, 0xb0, 0xa4, 0x86, 0xb2, 0x6c, 0x70, 0x91, 0x71, 0xad, 0xc8, 0x8b, 0xc0,
	0xf8, 0x5a, 0x20, 0x3b, 0xcb, 0x02, 0xf2, 0xe1, 0x2f, 0xc5, 0xd9, 0x01, 0x67, 0x4b, 0xba, 0xc9,
	0xd9, 0x1b, 0xf9, 0x4c, 0x6c, 0x93, 0xeb, 0xfc, 0xaf, 0xd5, 0x59, 0x48, 0x90, 0xaf, 0x05, 0x96,
	0xe0, 0xa9, 0x8a, 0x33, 0x02, 0x53, 0xb8, 0xab, 0x89, 0x82, 0x33, 0x86, 0x96, 0x9c, 0xbb, 0xee,
	0xf6, 0x16, 0xda, 0x6a, 0x9e, 0x9a, 0xeb, 0xd3, 0x67, 0x6d, 0x54, 0x9e, 0xd5, 0x01, 0xf8, 0xa3,
	0xfa, 0xcf, 0xdb, 0x60, 0xe2, 0x03, 0x4e, 0xd8, 0xec, 0x4b, 0x07, 0xe3, 0x71, 0x13, 0x32, 0x34,
	0x2b, 0x26, 0x12, 0x5e, 0x4e, 0x03, 0xeb, 0x0c, 0x2a, 0x35, 0x99, 0x28, 0x0d, 0xdd, 0x14, 0x83,
	0x96, 0x80, 0x32, 0x9a, 0xce, 0xb0, 0x5a, 0x2c, 0x68, 0xf7, 0xd0, 0x92, 0xb1, 0x1a, 0xa8, 0xbd,
	0x9d, 0x04, 0x53, 0xd1, 0xaa, 0xcb, 0x74, 0xb5, 0x89, 0x7e, 0xa5, 0xaf, 0x5a, 0x3c, 0x6c, 0xd7,
	0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xb3, 0x82, 0x21, 0x46, 0x8e, 0x03, 0x00, 0x00,
}
